game:
  push-22: false
gamblers:
  - gambler:
      name: "Gambler 1"
      bet-strategy: "two_bet_strategy"
      bankroll: 200
  - gambler:
      name: "Gambler 2"
dealer:
  play-strategy: "user_strat"
  bankroll: 1000
