game:
  minimum-bet: 5
  maximum-bet: 200
  # Whether to push on a value. In free bet blackjack this is most commonly 22. Default value is None.
  # push-on: 22
  # Blackjack value. Default value is 21.
  # blackjack: 21
# Configuration for gamblers; the players playing against the dealer.
gamblers:
  - gambler:
      # Name of the gambler. The name has to be unique among gamblers, and it can't be "Dealer". Required.
      name: "Gambler 1"
      # Bankroll of the gambler. Required.
      bankroll: 200
  - gambler:
      name: "Gambler 2"
      bankroll: 150
# Configuration for the dealer. The dealer has no bet strategy.
dealer:
  bankroll: 1000
